version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - pip install -r requirements.txt
      - printenv
      - echo $CODEBUILD_BUILD_NUMBER
      - python app_test.py $CODEBUILD_BUILD_NUMBER
